# Generated by Django 5.1.4 on 2024-12-26 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slackapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slackworkspace',
            name='channel_id',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slackworkspace',
            name='user_id',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
